---
- name: Ensure install directory exists
  file:
    path: "{{ gitea_install_dir }}"
    state: directory
    mode: '0755'
    owner: alexkgm
    group: alexkgm

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ gitea_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure custom assets directory exists
  file:
    path: "{{ gitea_install_dir }}/data/gitea/public/assets/img"
    state: directory
    mode: '0755'

- name: Check if custom logo.png exists locally
  delegate_to: localhost
  become: no
  stat:
    path: "roles/gitea/files/logo.png"
  register: logo_png_file

- name: Upload custom logo.png
  copy:
    src: logo.png
    dest: "{{ gitea_install_dir }}/data/gitea/public/assets/img/logo.png"
    mode: '0644'
  when: logo_png_file.stat.exists

- name: Upload custom favicon.png (if logo.png exists)
  copy:
    src: logo.png
    dest: "{{ gitea_install_dir }}/data/gitea/public/assets/img/favicon.png"
    mode: '0644'
  when: logo_png_file.stat.exists

- name: Check if custom logo.svg exists locally
  delegate_to: localhost
  become: no
  stat:
    path: "roles/gitea/files/logo.svg"
  register: logo_svg_file

- name: Upload custom logo.svg
  copy:
    src: logo.svg
    dest: "{{ gitea_install_dir }}/data/gitea/public/assets/img/logo.svg"
    mode: '0644'
  when: logo_svg_file.stat.exists

- name: Upload custom favicon.svg (if logo.svg exists)
  copy:
    src: logo.svg
    dest: "{{ gitea_install_dir }}/data/gitea/public/assets/img/favicon.svg"
    mode: '0644'
  when: logo_svg_file.stat.exists

- name: Start Gitea via Docker Compose
  command: docker compose pull
  args:
    chdir: "{{ gitea_install_dir }}"

- name: Start Gitea via Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ gitea_install_dir }}"

- name: Create initial admin user
  command: docker compose exec -T -u git gitea gitea admin user create --admin --username "{{ gitea_admin_user }}" --password "{{ gitea_admin_password }}" --email "{{ gitea_admin_email }}" --must-change-password=false
  args:
    chdir: "{{ gitea_install_dir }}"
  register: admin_create
  until: admin_create.rc == 0 or 'user already exists' in admin_create.stderr
  retries: 15
  delay: 5
  failed_when: admin_create.rc != 0 and 'user already exists' not in admin_create.stderr
  when: gitea_auto_init | bool
